title: தமிழ் கவிதை Site - Copied Kavithai and Tamil கவிதை Database
description: தமிழ் கவிதை Site - தமிழ்க்கவிதை தளங்கள், ஃபேஸ்புக் பக்கங்கள், மற்றும் ட்விட்டர் பக்கங்களில் இருந்து நகலெடுக்கப்பட்ட கவிதைகள் - Tamil Kavithai Database.
author:
  name: Tamil SMS,
  email: me@santhoshveer.com,
  url: https://kavithai.site/about/